<?php

function dna_menu() {
    $items['dna'] = array(
        'title' => 'Helix Matcher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dna_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function match_nucleotide($input) {
    if ($input == 'A') {
        return 'T';
    } elseif ($input == 'T') {
        return 'A';
    } elseif ($input == 'C') {
        return 'G';
    } elseif ($input == 'G') {
        return 'C';
    } else {
        return '';
    }
}    
