<?php

function dna_menu() {
    $items['dna'] = array(
        'title' => 'Helix Matcher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dna_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function dna_form() {
      $form['nucleotide_sequence'] = array(
            '#title' => 'Nucleotide Sequence',
            '#placeholder' => 'example: TAGCAT',
            '#type' => 'textfield',
            '#required' => TRUE,
            '#element_validate' => array('helix_matcher_form_validate'),
      );
      $form['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Match Um!'
      );
      return $form;
}

function match_nucleotide($input) {
    $broken_helix = str_split($input);
    $nucleotide_match_array = array();
    foreach($broken_helix as $nucleotide) {
        $capsed_nucleotide = strtoupper($nucleotide);
        if ($capsed_nucleotide == 'A') {
            array_push($nucleotide_match_array, 'T');
        } elseif ($capsed_nucleotide == 'T') {
            array_push($nucleotide_match_array, 'A');
        } elseif ($capsed_nucleotide == 'C') {
            array_push($nucleotide_match_array, 'G');
        } elseif ($capsed_nucleotide == 'G') {
            array_push($nucleotide_match_array, 'C');
        }
    }
    $nucleotide_match = join('', $nucleotide_match_array);
    return $nucleotide_match;
}
